#this dockerfile template comes from https://hub.docker.com/r/apache/superset
#https://malihasameen.medium.com/quick-setup-configure-superset-with-docker-a5cca3992b28
ARG BASE_IMAGE=apache/superset:3.0.1-py310
FROM $BASE_IMAGE
# Switching to root to install the required packages
USER root
COPY superset/db_engine_specs/radio-duckdb.py /app/superset/db_engine_specs/radio-duckdb.py

#fix CVE-2023-39417, see debian section - version12 for fix. https://scout.docker.com/vulnerabilities/id/CVE-2023-39417
#RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" &gt; /etc/apt/sources.list.d/pgdg.list'
#RUN apt install -y wget; apt install -y gnupg; wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - ; apt remove wget; apt remove gnupg;
RUN apt-get update && \
    apt-get remove -y postgresql-15=15.3-0+deb12u1 && \
    apt install -y postgresql-15=15.5-0+deb12u1 && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# installing the python db api driver to connect to radio-duck
RUN pip install district5

ENV ADMIN_USERNAME $ADMIN_USERNAME
ENV ADMIN_EMAIL $ADMIN_EMAIL
ENV ADMIN_PASSWORD $ADMIN_PASSWORD
ENV HEALTH_CHECK_INTERVAL $HEALTH_CHECK_INTERVAL

COPY --chown=superset superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

RUN mkdir /app/docker
RUN chown -R superset:superset /app/docker
COPY  ./superset_dir/docker/ /app/docker/
RUN chmod a+x /app/docker/*.sh

EXPOSE 8088

HEALTHCHECK CMD curl --fail http://localhost:8088 || exit 1

# Switching back to using the `superset` user
CMD [ "/app/docker/docker-ci.sh" ]
USER superset
