FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "SESSION_COOKIE_SAMESITE" : None
}

ENABLE_PROXY_FIX = True
#TALISMAN_ENABLED="False"
#SESSION_COOKIE_SAMESITE = None
#SUPERSET_SECRET_KEY="12312313D1acauGDSStiNuu2O1ZmK9E59QUPkRfB"