# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pytests_docker_build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: jaihind213/radio-duck

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade poetry
        poetry install
        poetry export --without-hashes --with dev --format=requirements.txt > requirements.txt 
        pip install -r requirements.txt
    - name: Lint code
      run: |
        echo "this is taken care as a pytest"
    - name: Test with pytest
      run: |
        pytest
    - name: Set up QEMU for cross-building
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Docker build image
      run: |
        DOCKER_VERSION=`cat pyproject.toml |grep version |grep -v python|grep -v target | awk '{print $3}' |sed -e "s/\"//g"`
        IMAGE_VERSION=${IMAGE_NAME}:${DOCKER_VERSION}
        echo "DOCKER_VERSION=$DOCKER_VERSION" >> $GITHUB_ENV
        echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
        docker buildx create --use
        # docker buildx build --platform=linux/amd64 -t $IMAGE_NAME:$DOCKER_VERSION -t $IMAGE_NAME:latest .
        # docker buildx build --platform=linux/arm64 -t $IMAGE_NAME:$DOCKER_VERSION -t $IMAGE_NAME:latest .
        echo "image name/version is $IMAGE_NAME/$DOCKER_VERSION"
        docker buildx build --platform=linux/x86_64,linux/amd64,linux/arm64 -t $IMAGE_NAME:$DOCKER_VERSION -t $IMAGE_NAME:latest .
    - name: Docker Scout
      id: docker-scout
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker/scout-action@v1
      with:
        command: cves
        #image: ${{  env.IMAGE_NAME }}:${{ DOCKER_VERSION }}
        ignore-unchanged: true
        only-severities: critical,high
        dockerhub-password: ${{ secrets.DHUB }}
        dockerhub-user: ${{ secrets.DHUB_USER }}
        exit-code: true
        only-fixed: true
        summary: true
      env:
        GITHUB_TOKEN: ${{ secrets.GTOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DHUB_USER }}
        password: ${{ secrets.DHUB }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/x86_64,linux/amd64,linux/arm64
        push: true
        #tags: jaihind213/radio-duck:latest
        tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_VERSION }}
