# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pytests_docker_build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade poetry
        poetry --version
        pwd
        ls -lah
        poetry install
        poetry export --without-hashes --format=requirements.txt > requirements.txt
        pip install -r requirements.txt
    - name: Lint code
      run: |
        echo "this is taken care as a pytest"
    - name: Test with pytest
      run: |
        pytest
    - name: Docker build
      run: |
        DOCKER_VERSION=`cat pyproject.toml |grep version |grep -v python|grep -v target | awk '{print $3}' |sed -e "s/\"//g"`
        echo "DOCKER_VERSION as $DOCKER_VERSION"
        bash buildDocker.sh $DOCKER_VERSION
