# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pytests_docker_build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade poetry
        poetry install
        poetry export --without-hashes --with dev --format=requirements.txt > requirements.txt 
        pip install -r requirements.txt
        pwd
        ls -lah
        pip show pytest
    - name: Lint code
      run: |
        echo "this is taken care as a pytest"
    - name: Test with pytest
      run: |
        pytest
    - name: Set up QEMU for cross-building
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Docker build image
      run: |
        DOCKER_VERSION=`cat pyproject.toml |grep version |grep -v python|grep -v target | awk '{print $3}' |sed -e "s/\"//g"`
        export DOCKER_VERSION=0.0.1
        echo "Using Docker image version as $DOCKER_VERSION"
        docker buildx create --use
        # docker buildx build --platform=linux/amd64 -t ${{ IMAGE_NAME }}:$DOCKER_VERSION -t $IMAGE_NAME:latest .
        # docker buildx build --platform=linux/arm64 -t ${{ IMAGE_NAME }}:$DOCKER_VERSION -t $IMAGE_NAME:latest .
        docker buildx build --platform=linux/x86_64 -t ${{ IMAGE_NAME }}:$DOCKER_VERSION -t $IMAGE_NAME:latest .
        # bash docker_sec_check.sh
    - name: Docker Scout
      id: docker-scout
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker/scout-action@v1
      with:
        command: cves
        #image: ${{ IMAGE_NAME }}:${{ DOCKER_VERSION }}
        image: jaihind213/radio-duck:0.0.1
        ignore-unchanged: true
        only-severities: critical,high
        dockerhub-password: ${{ secrets.DHUB }}
        dockerhub-user: ${{ secrets.DHUB_USER }}
        exit-code: true
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/x86_64
        push: true
        tags: jaihind213/radio-duck:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DHUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DHUB }}
